pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:victorvisionpd/lumen-protocol.git
          - cd lumen-protocol.git
          - git push --mirror git@github.com:victorvision/Lumen-Protocol.git
